# Lapack package

include(ExternalProject)

set(LAPACK_SOURCE_DIR ${MAIN_SOURCE_DIR}/lapack)
set(LAPACK_BINARY_DIR ${MAIN_BINARY_DIR}/lapack)
set(LAPACK_INSTALL_PREFIX ${MAIN_INSTALL_PREFIX}/lapack)

message(STATUS "Install Lapack release 3.10.1")

ExternalProject_Add(Lapack
    GIT_REPOSITORY https://github.com/Reference-LAPACK/lapack.git
    GIT_TAG 32b062a33352e05771dcc01b981ebe961bf2e42f # release 3.10.1
    GIT_SHALLOW TRUE
    GIT_PROGRESS TRUE
    SOURCE_DIR ${LAPACK_SOURCE_DIR}
    BINARY_DIR ${LAPACK_BINARY_DIR}
    CMAKE_ARGS -DBUILD_SHARED_LIBS=ON -DCMAKE_C_COMPILER=${CMAKE_C_COMPILER} -DCMAKE_CXX_COMPILER=${CMAKE_CXX_COMPILER} -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE} -DCMAKE_INSTALL_PREFIX=${LAPACK_INSTALL_PREFIX}
    )
