# Metis package

include(ExternalProject)

set(METIS_SOURCE_DIR ${MAIN_SOURCE_DIR}/metis)
set(METIS_BINARY_DIR ${MAIN_BINARY_DIR}/metis)
set(METIS_INSTALL_PREFIX ${MAIN_INSTALL_PREFIX}/metis)

message(STATUS "Install Metis release 5.1.0")

ExternalProject_Add(Metis
    GIT_REPOSITORY https://github.com/fvicini/metis.git
    GIT_TAG 30ec18492217ec8e5d675e6c950bb74d94f3dc18 # release 5.1.1
    GIT_SHALLOW TRUE
    GIT_PROGRESS TRUE
    SOURCE_DIR ${METIS_SOURCE_DIR}
    BINARY_DIR ${METIS_BINARY_DIR}
    CMAKE_ARGS -DCMAKE_C_COMPILER=${CMAKE_C_COMPILER} -DCMAKE_CXX_COMPILER=${CMAKE_CXX_COMPILER} -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE} -DCMAKE_INSTALL_PREFIX=${METIS_INSTALL_PREFIX}
    )
